<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Assistant extends Model
{
    use HasFactory;

    public static $initial_data = [
        [
            "name" => "Adinda sekar Santia",
            "code" => "DND",
            "gender" => "female",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1Bx-XDJ4aUhCBoTa2dBLT9ndmU6_M_ea_?usp=sharing",
        ],
        [
            "name" => "Ahdan Abdulfattah Rizqi",
            "code" => "AHD",
            "gender" => "male",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1g-1WHYj6XQ-NNEXmLJJkwfjzuxP7Uv5n?usp=sharing",
        ],
        [
            "name" => "Alfarizi Wiranata",
            "code" => "ZIW",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1J8p_5QQTS2Mni6R3EZAVFgiK32h1mN4c?usp=sharing",
        ],
        [
            "name" => "Alfred Komuna",
            "code" => "AKM",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1LH5pLpy5Z8Lj5gLO_wyRWt3YKD_XM18S?usp=sharing",
        ],
        [
            "name" => "Aliya Mahmuda Putri",
            "code" => "AMP",
            "gender" => "female",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1_Wk5FkUo9IW9RziL1IK4RUR1uA_HSfto?usp=sharing",
        ],
        [
            "name" => "Andi Muhammad Fachri",
            "code" => "AMF",
            "gender" => "male",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1VOQpav3oDlF3mL5eMW8a3sbvQN5cDzcD?usp=sharing",
        ],
        [
            "name" => "Andre Prasetyo",
            "code" => "AND",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1ldg96uBAW8ZiK1fdJnqDfgyc4SXMaH1c?usp=sharing",
        ],
        [
            "name" => "Andreas Alberto Sitorus",
            "code" => "AAL",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1hjGtXni2tl7lUjjXBvA7zxZud_fsyjfy?usp=sharing",
        ],
        [
            "name" => "Andy Law Exaudy Simbolon",
            "code" => "LAW",
            "gender" => "male",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1UwuvbNB-4asJ7WJCabnSuRqL7FeDnfZR?usp=sharing",
        ],
        [
            "name" => "Anis Ratna Sari",
            "code" => "CRT",
            "gender" => "female",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1ieCXCTdGLB6ja4aiNt9TPShakMjcxtHb?usp=sharing",
        ],
        [
            "name" => "Anita Rosdina Nasution",
            "code" => "CHO",
            "gender" => "female",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1c-ZUnJfclV59NLEDAy3GiVwXwKJRmPkr?usp=sharing",
        ],
        [
            "name" => "Annisa Ayu Lestari",
            "code" => "SEU",
            "gender" => "female",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1_EOCqmPInO8zwZjt_743IHpg-g3AHZsx?usp=sharing",
        ],
        [
            "name" => "Arsyad Dhiauddin",
            "code" => "ITB",
            "gender" => "male",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1q6ym53Z1v4tsNATQ0WALQy-hx-JU3pDb?usp=sharing",
        ],
        [
            "name" => "Aurellia Fieldza Sendyartha",
            "code" => "AFS",
            "gender" => "female",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1HnYDA_r0KGZYHWsLkD2O92FQf2mo02yB?usp=sharing",
        ],
        [
            "name" => "Averina Fidelia Aqiilah Dizaramadhani",
            "code" => "VRN",
            "gender" => "female",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1XiAGYBtmzcn1o2-5TrOJMpJHP17OWDlS?usp=sharing",
        ],
        [
            "name" => "Awal Sholeh Subarkah",
            "code" => "AWL",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1VOFkaqB9G3TKWPbcWMuqfUNU_ta5Sxvr?usp=sharing",
        ],
        [
            "name" => "Ayu Sekar Safitri",
            "code" => "AYS",
            "gender" => "female",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1-t4AjZUO-SxWwqnUO6cvEj-dV3w56lRI?usp=sharing",
        ],
        [
            "name" => "Azizah Luthfiah",
            "code" => "FIA",
            "gender" => "female",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1FjIdvgrW2TMVtdPv_OoQc9s3CndQ_bpj?usp=sharing",
        ],
        [
            "name" => "Bagas Wibisono",
            "code" => "BEW",
            "gender" => "male",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1t9yZ7rukuS6Mb8htwUOwCod2tdoRCTAf?usp=sharing",
        ],
        [
            "name" => "Baharuddin Nur Maulana",
            "code" => "LAN",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/15aNharAaK-yDZy6YGz75apPLojTwC3yu?usp=sharing",
        ],
        [
            "name" => "Bintang Kriesna Nugraha",
            "code" => "BIN",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1C_WbMpUpPP7CD3nBE31Ujnb4EylN-wyX?usp=sharing",
        ],
        [
            "name" => "Cahaya Irham Wirawan",
            "code" => "CCC",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1RCDKGZUUNoPk9Vr71I4avsdWLeyKuKYW?usp=sharing",
        ],
        [
            "name" => "Candra Budiman",
            "code" => "CAN",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1seB6uA_bAnKX9nB3StPIiRNnL_Ytt6dm?usp=sharing",
        ],
        [
            "name" => "Christian Halomoan Siregar",
            "code" => "CHR",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1VkTOqnl-TA94zig7yibGt6ZTasZZdiqZ?usp=sharing",
        ],
        [
            "name" => "Cyla Rahmania",
            "code" => "CRA",
            "gender" => "female",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1G4dW80KCDFIT6MPUWXIOWi9oi0k5y_px?usp=sharing",
        ],
        [
            "name" => "Delatifa Putri Sugandi",
            "code" => "DFA",
            "gender" => "female",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1IAZohKSa_kPvRL91lEnJQ6gu24l4pTGA?usp=sharing",
        ],
        [
            "name" => "Denny Tri Sukmono",
            "code" => "DEY",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1m9PXUwkn8-FRew0EalktbjYrpXeXsAjP?usp=sharing",
        ],
        [
            "name" => "Deva Aulia Putri Oktavia",
            "code" => "DVA",
            "gender" => "female",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/12BXvVGCOd3hyjZjbQ1fwJ7JdpGLXYgZ3?usp=sharing",
        ],
        [
            "name" => "Dewi Iswaratika",
            "code" => "ARA",
            "gender" => "female",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1yCSCf9j000bmUwZsIqWF_Qyk43DGqqKN?usp=sharing",
        ],
        [
            "name" => "Dhimas Chandra Bagaskara",
            "code" => "DAS",
            "gender" => "male",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1WX67P_NTn2vH_Q3xcMlZcxAmZP_eEJtM?usp=sharing",
        ],
        [
            "name" => "Dyka Khairullah Zamhari",
            "code" => "DKZ",
            "gender" => "male",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1qwTfSsgPNrlWu19eYPNn7m3jPEhvIV0x?usp=sharing",
        ],
        [
            "name" => "Elsi Purbowati",
            "code" => "EPW",
            "gender" => "female",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/11W2_5DAu7SL0ljzpaLDcI0sh0RZxHwY5?usp=sharing",
        ],
        [
            "name" => "Faisa Atharani Nugroho",
            "code" => "FAY",
            "gender" => "female",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1_kcM7Kni3QzQSATiiH3ZvSnJmOW2GWWX?usp=sharing",
        ],
        [
            "name" => "Fajar Nur Raudhidarma",
            "code" => "RDM",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1dFLBmyMdEkRornFwCmpaRmeqYfNm8QFf?usp=sharing",
        ],
        [
            "name" => "Fandi Achmad",
            "code" => "FAC",
            "gender" => "male",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1jjjj_Ev_n_pm5_wZRvYFK8gRi6zBSfvF?usp=sharing",
        ],
        [
            "name" => "Faradisya Heris",
            "code" => "DSY",
            "gender" => "female",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1sELVh-gY7ppzgaNX14-lWZfHs_R5ryTH?usp=sharing",
        ],
        [
            "name" => "Farah Hanifah",
            "code" => "FAR",
            "gender" => "female",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1_smScettVK4UdQmzPMeEZDSeqw6vLpJr",
        ],
        [
            "name" => "Fariz Erawan",
            "code" => "FAZ",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1tsgjKmGnWH8m0dsjL0NAhjTxPdlJLU7p",
        ],
        [
            "name" => "Fath Muhammad Isham",
            "code" => "PED",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1Brr-WitpwO1Np3RwkRzQBAX_UgRlRrI5",
        ],
        [
            "name" => "Felix",
            "code" => "LIX",
            "gender" => "male",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1ELKc3jgv4I5LZ9T7_vKtUEf1ksGmM2C9",
        ],
        [
            "name" => "Fika Triana",
            "code" => "FIK",
            "gender" => "female",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1VdmoqSIl06THmpjsE4b9p1YHnClKCUDv",
        ],
        [
            "name" => "Fildza Nadhilah Nursalam",
            "code" => "NAD",
            "gender" => "female",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1pJH0M9qF1FWuhQFxzIq6W4qcpFo6gahD",
        ],
        [
            "name" => "Firda Aulya Syahrul",
            "code" => "FAS",
            "gender" => "female",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1PY9kb-L24ue0KAB5jzMv4tU6frdKwswq",
        ],
        [
            "name" => "Gelar Gemilang Zulkarnain",
            "code" => "GGZ",
            "gender" => "male",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1H0p9QRmI7_Vq3IkJlTioIhltFws8SUnk",
        ],
        [
            "name" => "Hafid Ikhsan Arifin",
            "code" => "HAI",
            "gender" => "male",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1ECrJSeK-0QNfpHCnI9dyEfq0RrGwTgqL",
        ],
        [
            "name" => "Hafizhah Khaerani",
            "code" => "HKR",
            "gender" => "female",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1xWFcipwU2Dytg-KbmT3plBnchm865dxg",
        ],
        [
            "name" => "Halvionita Puspitasari Dewi",
            "code" => "VIO",
            "gender" => "female",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1lTt7UHBQLfGBzwpa5jcGXOlAhZyoILfE",
        ],
        [
            "name" => "I Deo Kelvin Aprianta",
            "code" => "LVN",
            "gender" => "male",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/13uYOSmm7k04Df2Id0NOCzxIordPq7WF7",
        ],
        [
            "name" => "Iftikar Fadhlirohman S.",
            "code" => "IFR",
            "gender" => "male",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1BHDOEXUYNoWdHxpofDaRvDBH-WHriuh-?usp=sharing",
        ],
        [
            "name" => "Ihsan Maulidin",
            "code" => "ENG",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1vSYV1oIrwYBqNLnjGQiBeFai4cZUAkYQ?usp=sharing",
        ],
        [
            "name" => "Ilham Nadiyansyah Firdaus",
            "code" => "IND",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/17Uje2EQleaPuJlcdDuj6rl4Yh2J6BCVL?usp=sharing",
        ],
        [
            "name" => "Indah Indriani",
            "code" => "DAH",
            "gender" => "female",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1W-MXMnpFRtndRtMzK7qpa2nKgpS83MsF?usp=sharing",
        ],
        [
            "name" => "Ivan Satrio Pamungkas",
            "code" => "RIO",
            "gender" => "male",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1lLpZ9soiNJ5fopIuKszezbbh9hc6AMed?usp=sharing",
        ],
        [
            "name" => "Izzu Zantya Fawwas",
            "code" => "IZZ",
            "gender" => "male",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1ROUa2JX0L0MEMRNl_JJT-khR5pWeucTM?usp=sharing",
        ],
        [
            "name" => "Jihan Salsabila",
            "code" => "JIH",
            "gender" => "female",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1_6Ma8ktUZhgB71mLAeohBUA6E_GVLSxe?usp=sharing",
        ],
        [
            "name" => "M. Fadel Mustamin",
            "code" => "DEE",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1bjpVWPfSszP8eKOnhw3zfFuFZRv446-P?usp=sharing",
        ],
        [
            "name" => "M. Hasyim Abdillah P.",
            "code" => "HYM",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1f7LaOwdjfWBp3dmrhfCJ8KDzvvlWzdSa?usp=sharing",
        ],
        [
            "name" => "Maria Emerald Nainggolan",
            "code" => "EMA",
            "gender" => "female",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1K_XGWezq8ITGyMDAgaAj-r5y6eDww9yR?usp=sharing",
        ],
        [
            "name" => "Maulana Fauzan Athalla Halinda",
            "code" => "ATA",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/16hR9Dkt1mWUHeRr5d0SopHvrVqtwIUmY?usp=sharing",
        ],
        [
            "name" => "Melinda Saleha",
            "code" => "MEL",
            "gender" => "female",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/14MfDw720bDKYG9PP-88l5YBcLWL5e_wa",
        ],
        [
            "name" => "Melodiva Madao",
            "code" => "MNM",
            "gender" => "female",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1N7BbOr9hK0emduhtKGzNFemQ5na4otBl",
        ],
        [
            "name" => "Mikail Rizkyena",
            "code" => "MKC",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1yxObQ9lzZjz-Gk2lTK5AavwtZPctC-0N",
        ],
        [
            "name" => "Mohammad Ikhwan Mahbuby",
            "code" => "BOB",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/18ibrI0ApF-gyPWNzB2ezDl2OdjFWV5Fe",
        ],
        [
            "name" => "Monalisa Pratiwi",
            "code" => "MPR",
            "gender" => "female",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1ADYkipkKE0uz9BahZPwd1bJTh1eORnkI",
        ],
        [
            "name" => "Muhammad Diponegoro St Ropawiro",
            "code" => "MDS",
            "gender" => "male",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/19DJ50epyJuzmdInZuF4n2wgn5_PXnw17",
        ],
        [
            "name" => "Muhammad Fikri Reynaldi",
            "code" => "LDI",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1z0Lnmb8_DGp19rDt7BXTplVhs9kLTCRM",
        ],
        [
            "name" => "Muhammad Fuad Wirahilmi",
            "code" => "WRA",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1273BAfK03cF6duNxdG_ELmCEIqYo50qg",
        ],
        [
            "name" => "Muhammad Ilham Firdaus",
            "code" => "HAM",
            "gender" => "male",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/15jNIyXnn0GXvakFr4rNaE6LSTgqpjvNr",
        ],
        [
            "name" => "Muhammad Iqbal",
            "code" => "IBG",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/12Hd_IJYyPEM7nnJnjz3S9ANjv0U8hKXQ",
        ],
        [
            "name" => "Muhammad Zaki",
            "code" => "MZH",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1v1H3jUdqJvSPRpDA7Xy5wQgmEwFvwH5S",
        ],
        [
            "name" => "Nadhilah Rahmatia Kautsari",
            "code" => "NDL",
            "gender" => "female",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/13xUXZrqThoKL0OCJiaucDpw3odDglaJB",
        ],
        [
            "name" => "Namira Fasya Rahim",
            "code" => "MIA",
            "gender" => "female",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1Wp7lhGtDoqQZlujawc231zilzboNRQ28",
        ],
        [
            "name" => "Nathaniel Syalomta",
            "code" => "ABE",
            "gender" => "male",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1DrGplknmWxtyc4WoGwRIk9DT0VphfF1X",
        ],
        [
            "name" => "Novia Walrahmadani",
            "code" => "NOV",
            "gender" => "female",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/11GD-98fIXBZIvGlovXGcRIMITMEh7m2U",
        ],
        [
            "name" => "Nur Yudha Kurnia Ramadhan",
            "code" => "YDH",
            "gender" => "male",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1SP5tOOT3qGFz3cM-brpCPGabu6sXrIkg",
        ],
        [
            "name" => "Nurul Amelia",
            "code" => "ELL",
            "gender" => "female",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1vY1IxpE7wfM-kAo8RyB3K0o6L92lPEF0",
        ],
        [
            "name" => "Pratiwi Novayanti",
            "code" => "PNY",
            "gender" => "female",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1Gv3f-NG7xhLDYhn-OcMNfcVfynDEmToJ",
        ],
        [
            "name" => "Putri Indra Wahyuningsih",
            "code" => "PUT",
            "gender" => "female",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/11xzCfmwSlIU1G5q29N9Eehwacq3T3Vut",
        ],
        [
            "name" => "Putu Dicky Marthree Sapodu Merta",
            "code" => "DKY",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1s8WJh1Lz_wBiUb6X_VB-zuPiVBB2LIot?usp=sharing",
        ],
        [
            "name" => "Qualita Imani Pradharona",
            "code" => "RON",
            "gender" => "female",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1P923FUmEDfKej-u7R8CsplTDBfmJuIOs?usp=sharing",
        ],
        [
            "name" => "Raden Satria Daffa Fareza",
            "code" => "FRZ",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/17F0NoUuD3X5CmDhIWL28sKgelpyfxLoT?usp=sharing",
        ],
        [
            "name" => "Rahma Sabilla Ashar",
            "code" => "BLA",
            "gender" => "female",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1P0g1-Gg8eyrpGJ-zcRjRjlVqY2ym6bqI?usp=sharing",
        ],
        [
            "name" => "Raisa Afifah",
            "code" => "RAF",
            "gender" => "female",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1U1HSKu0QQBTjPUO6NI3wd6Qktm1Algu2?usp=sharing",
        ],
        [
            "name" => "Raissa Nur Andiva",
            "code" => "RNA",
            "gender" => "female",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/11l9qn_HflWSLjC6P5qjqqSQxK9yBDCLc?usp=sharing",
        ],
        [
            "name" => "Rayhan Erdyarahman",
            "code" => "REY",
            "gender" => "male",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1sV6Tw6nLVVzlNqXCNDZcKGIAn9h71GMq?usp=sharing",
        ],
        [
            "name" => "Rianta Athallah Dharmmesta",
            "code" => "NTA",
            "gender" => "male",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1wTtgVK6S7s-6StZLM1x8ODUKE6h6DTus?usp=sharing",
        ],
        [
            "name" => "Richardo Praystihan Sitepu",
            "code" => "RCO",
            "gender" => "male",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1Gf40u8PhyZGG5A_tbLsyoZaj4bcgJtoX?usp=sharing",
        ],
        [
            "name" => "Rindha Ayu Kusumaningputri",
            "code" => "RIN",
            "gender" => "female",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/16RZnZ7opWOa5Qo9IVeqCN56Lt-X6GwQC?usp=sharing",
        ],
        [
            "name" => "Ryan Vianatha",
            "code" => "AGV",
            "gender" => "male",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/10QfpVmrxJxF9SgtoeQmyvwa3sj07ISFh?usp=sharing",
        ],
        [
            "name" => "Saddam Adri Perdana",
            "code" => "DAM",
            "gender" => "male",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1SuC4me7324-w5lB5nlKMXdrdejfiuAeB?usp=sharing",
        ],
        [
            "name" => "Sang Ayu Ketut Devi Saraswati",
            "code" => "SRS",
            "gender" => "female",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1jTYZ962Zh4fbdZS2-R2g74oqGCM0DgXJ?usp=sharing",
        ],
        [
            "name" => "Selly Lastanila",
            "code" => "SYL",
            "gender" => "female",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/12TKkAQQCF1eW8sYZhtBcKgp1IZQcgqir?usp=sharing",
        ],
        [
            "name" => "Siti Ashila Farikha Mayundri",
            "code" => "CIA",
            "gender" => "female",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1q_8Y_aoi7RysAdSLHIYDUQJELXurPkuG?usp=sharing",
        ],
        [
            "name" => "Sitti Amalia Suhandini",
            "code" => "DIN",
            "gender" => "female",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1MgnDZsibmLAHhmUNX8g402KHbrcvzyIe?usp=sharing",
        ],
        [
            "name" => "Syafiq Fatih Basalamah",
            "code" => "TIH",
            "gender" => "male",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1G2aCA_yL28pKKP5o7Q314UesWJoJC7u5?usp=sharing",
        ],
        [
            "name" => "Syifa Rezki Fauziah",
            "code" => "CIP",
            "gender" => "female",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1weBKreHkr_iTfiOTRmWRLZ268bkSJ6W6?usp=sharing",
        ],
        [
            "name" => "Tamma Hasya Gemilang",
            "code" => "TMA",
            "gender" => "male",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1OtiadWoJOl4_cbbXSypmf09_mcJ3m7ev?usp=sharing",
        ],
        [
            "name" => "Tania Verasta",
            "code" => "TAN",
            "gender" => "female",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1mVYc13PKePPJln7V0WDZ0e0UDixNB_Sv?usp=sharing",
        ],
        [
            "name" => "Thalita Dewi Rahmaniar",
            "code" => "THA",
            "gender" => "female",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1F53snSTzB-X8uds8KiqEvholDIALEgcZ?usp=sharing",
        ],
        [
            "name" => "Umi Nihayah",
            "code" => "AYA",
            "gender" => "female",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1-9EYZlbJD7-PvtRGPOPW51qckVKUb-nd?usp=sharing",
        ],
        [
            "name" => "Viny Aulia Sabilla",
            "code" => "VAS",
            "gender" => "female",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1tla_NgazZPKmbW0u5-a9BfIJQKIlm94j?usp=sharing",
        ],
        [
            "name" => "Yonathan Verrel Lou Drie",
            "code" => "LOU",
            "gender" => "male",
            "standing" => "senior",
            "feedback_link" => "https://drive.google.com/drive/folders/1Zdj9sa-OepifI8OUJKIE1SZtyXzHo0WZ?usp=sharing",
        ],
        [
            "name" => "Zalfa Aurellia",
            "code" => "ZAL",
            "gender" => "female",
            "standing" => "junior",
            "feedback_link" => "https://drive.google.com/drive/folders/1aIrbLvtz4_uimI2vVBJ2_b-45j7dP4jR?usp=sharing",
        ]
    ];
}
