import { AssistantLevel, Gender } from 'src/core/constants';

export const assistantSeeder = [
  {
    name: 'Alfarizi Wiranata',
    code: 'ZIW',
    phoneNumber: '081268403497',
    lineId: 'alfanata11',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1J8p_5QQTS2Mni6R3EZAVFgiK32h1mN4c?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Alfred Komuna',
    code: 'AKM',
    phoneNumber: '085146274221',
    lineId: 'alfred808',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1LH5pLpy5Z8Lj5gLO_wyRWt3YKD_XM18S?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Aliya Mahmuda Putri',
    code: 'AMP',
    phoneNumber: '081321612244',
    lineId: 'aliyamputri',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1_Wk5FkUo9IW9RziL1IK4RUR1uA_HSfto?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Andreas Alberto Sitorus',
    code: 'AAL',
    phoneNumber: '081361714536',
    lineId: 'andreas_alberto',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1hjGtXni2tl7lUjjXBvA7zxZud_fsyjfy?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Annisa Ayu Lestari',
    code: 'SEU',
    phoneNumber: '082255480331',
    lineId: 'annisayutari',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1_EOCqmPInO8zwZjt_743IHpg-g3AHZsx?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Awal Sholeh Subarkah',
    code: 'AWL',
    phoneNumber: '085659541819',
    lineId: 'wacawow',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1VOFkaqB9G3TKWPbcWMuqfUNU_ta5Sxvr?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Ayu Sekar Safitri',
    code: 'AYS',
    phoneNumber: '081809609592',
    lineId: 'ayusekarsafitri',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1-t4AjZUO-SxWwqnUO6cvEj-dV3w56lRI?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Baharuddin Nur Maulana',
    code: 'LAN',
    phoneNumber: '085292633237',
    lineId: 'lana9807',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/15aNharAaK-yDZy6YGz75apPLojTwC3yu?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Bintang Kriesna Nugraha',
    code: 'BIN',
    phoneNumber: '081321260271',
    lineId: 'bkriesna',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1C_WbMpUpPP7CD3nBE31Ujnb4EylN-wyX?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Nurul Amelia',
    code: 'RAP',
    phoneNumber: '085228338362',
    lineId: 'nurulamelia_638',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1vY1IxpE7wfM-kAo8RyB3K0o6L92lPEF0',
    profilePictureUrl: null,
  },
  {
    name: 'Christian Halomoan Siregar',
    code: 'CHR',
    phoneNumber: '081297417209',
    lineId: 'christianhs_',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1VkTOqnl-TA94zig7yibGt6ZTasZZdiqZ?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Cyla Rahmania',
    code: 'CRA',
    phoneNumber: '081294269594',
    lineId: 'cylarahmania24',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1G4dW80KCDFIT6MPUWXIOWi9oi0k5y_px?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Delatifa Putri Sugandi',
    code: 'DFA',
    phoneNumber: '082297865232',
    lineId: 'delatifa21_',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1IAZohKSa_kPvRL91lEnJQ6gu24l4pTGA?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Denny Tri Sukmono',
    code: 'DEY',
    phoneNumber: '085156719015',
    lineId: 'dennytrisukmono',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1m9PXUwkn8-FRew0EalktbjYrpXeXsAjP?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Faisa Atharani Nugroho',
    code: 'FAY',
    phoneNumber: '085280166420',
    lineId: 'faishaa_',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1_kcM7Kni3QzQSATiiH3ZvSnJmOW2GWWX?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Fajar Nur Raudhidarma',
    code: 'RDM',
    phoneNumber: '0895344703822',
    lineId: 'fajarnur.raudhidarma',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1dFLBmyMdEkRornFwCmpaRmeqYfNm8QFf?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Farah Hanifah',
    code: 'FAR',
    phoneNumber: '081222468002',
    lineId: '_farahhn_',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1_smScettVK4UdQmzPMeEZDSeqw6vLpJr',
    profilePictureUrl: null,
  },
  {
    name: 'Fariz Erawan',
    code: 'FAZ',
    phoneNumber: '082268759408',
    lineId: 'farizerawan24',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1tsgjKmGnWH8m0dsjL0NAhjTxPdlJLU7p',
    profilePictureUrl: null,
  },
  {
    name: 'Fath Muhammad Isham',
    code: 'PED',
    phoneNumber: '085973069306',
    lineId: 'fathmisham',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1Brr-WitpwO1Np3RwkRzQBAX_UgRlRrI5',
    profilePictureUrl: null,
  },
  {
    name: 'Selly Lastanila',
    code: 'SYL',
    phoneNumber: '082361839080',
    lineId: 'sellylastanila09',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/12TKkAQQCF1eW8sYZhtBcKgp1IZQcgqir?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Rindha Ayu Kusumaningputri',
    code: 'RIN',
    phoneNumber: '081254807409',
    lineId: 'riindha541',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/16RZnZ7opWOa5Qo9IVeqCN56Lt-X6GwQC?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Raissa Nur Andiva',
    code: 'RNA',
    phoneNumber: '0895421015953',
    lineId: 'raissandiva',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/11l9qn_HflWSLjC6P5qjqqSQxK9yBDCLc?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Raden Satria Daffa Fareza',
    code: 'FRZ',
    phoneNumber: '081290804290',
    lineId: 'daffa70',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/17F0NoUuD3X5CmDhIWL28sKgelpyfxLoT?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Putu Dicky Marthree Sapodu Merta',
    code: 'DKY',
    phoneNumber: '085339327744',
    lineId: 'Dickymsm',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1s8WJh1Lz_wBiUb6X_VB-zuPiVBB2LIot?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Putri Indra Wahyuningsih',
    code: 'PUT',
    phoneNumber: '0895390671721',
    lineId: 'putrii_ndra',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/11xzCfmwSlIU1G5q29N9Eehwacq3T3Vut',
    profilePictureUrl: null,
  },
  {
    name: 'Firda Aulya Syahrul',
    code: 'FAS',
    phoneNumber: '082245628326',
    lineId: 'firdasyahrul',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1PY9kb-L24ue0KAB5jzMv4tU6frdKwswq',
    profilePictureUrl: null,
  },
  {
    name: 'Nadillah Rahmatia Kautsari',
    code: 'NDL',
    phoneNumber: '081932815995',
    lineId: 'ndlrh',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/13xUXZrqThoKL0OCJiaucDpw3odDglaJB',
    profilePictureUrl: null,
  },
  {
    name: 'Muhammad Zaki',
    code: 'MZH',
    phoneNumber: '081224606006',
    lineId: 'mzaki22',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1v1H3jUdqJvSPRpDA7Xy5wQgmEwFvwH5S',
    profilePictureUrl: null,
  },
  {
    name: 'Muhammad Iqbal',
    code: 'IBG',
    phoneNumber: '087834332582',
    lineId: 'iqbalopi123',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/12Hd_IJYyPEM7nnJnjz3S9ANjv0U8hKXQ',
    profilePictureUrl: null,
  },
  {
    name: 'Muhammad Fuad Wirahilmi',
    code: 'WRA',
    phoneNumber: '082112321885',
    lineId: 'wirahilmi_15',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1273BAfK03cF6duNxdG_ELmCEIqYo50qg',
    profilePictureUrl: null,
  },
  {
    name: 'Mohammad Ikhwan Mahbuby',
    code: 'BOB',
    phoneNumber: '085259271105',
    lineId: 'bengalan.com',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/18ibrI0ApF-gyPWNzB2ezDl2OdjFWV5Fe',
    profilePictureUrl: null,
  },
  {
    name: 'Mikail Rizkyena',
    code: 'MKC',
    phoneNumber: '081296335014',
    lineId: 'mikail2001',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1yxObQ9lzZjz-Gk2lTK5AavwtZPctC-0N',
    profilePictureUrl: null,
  },
  {
    name: 'M. Hasyim Abdillah P.',
    code: 'HYM',
    phoneNumber: '0895410904253',
    lineId: '.m_hasyim_a_p.',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1f7LaOwdjfWBp3dmrhfCJ8KDzvvlWzdSa?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'M. Fadel Mustamin',
    code: 'DEE',
    phoneNumber: '082393393143',
    lineId: 'muhammadfadelashar',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1bjpVWPfSszP8eKOnhw3zfFuFZRv446-P?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Melodiva Madao',
    code: 'MNM',
    phoneNumber: '0811425472',
    lineId: 'melodi.m15',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1N7BbOr9hK0emduhtKGzNFemQ5na4otBl',
    profilePictureUrl: null,
  },
  {
    name: 'Indah Indriani',
    code: 'DAH',
    phoneNumber: '081904548432',
    lineId: 'iindaaahindrianiii',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1W-MXMnpFRtndRtMzK7qpa2nKgpS83MsF?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Ilham Nadiyansyah Firdaus',
    code: 'IND',
    phoneNumber: '085720143584',
    lineId: 'ayiilham44',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/17Uje2EQleaPuJlcdDuj6rl4Yh2J6BCVL?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Ihsan Maulidin',
    code: 'ENG',
    phoneNumber: '081907811685',
    lineId: 'ea4a916c',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1vSYV1oIrwYBqNLnjGQiBeFai4cZUAkYQ?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Hafid Ikhsan Arifin',
    code: 'HAI',
    phoneNumber: '0895364909798',
    lineId: 'hafidikhsana',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1ECrJSeK-0QNfpHCnI9dyEfq0RrGwTgqL',
    profilePictureUrl: null,
  },
  {
    name: 'Saddam Adri Perdana',
    code: 'DAM',
    phoneNumber: '081213699753',
    lineId: 'saddamace26',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1SuC4me7324-w5lB5nlKMXdrdejfiuAeB?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Candra Budiman',
    code: 'DRA',
    phoneNumber: '081224309589',
    lineId: 'candrab810',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1seB6uA_bAnKX9nB3StPIiRNnL_Ytt6dm?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Adam Hadi Pratama',
    code: 'ADR',
    phoneNumber: '081334858350',
    lineId: 'adamhadip7',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Aditiya Nicola Putra',
    code: 'COO',
    phoneNumber: '081311859811',
    lineId: '12adiputra',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Alifia Mutiara Rahma',
    code: 'AMR',
    phoneNumber: '085155121460',
    lineId: 'alifiamutiarhm',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Alvito Ahmad Cannavaro Idham',
    code: 'ALV',
    phoneNumber: '081321249470',
    lineId: 'blakelolz',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Aneira Shafi Luthfia',
    code: 'ANE',
    phoneNumber: '082110665986',
    lineId: 'aneirashafi',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Dhifan Dwi Nugraha',
    code: 'PAN',
    phoneNumber: '081278428088',
    lineId: '292106',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Fadhlul Ariqi',
    code: 'FAD',
    phoneNumber: '082283257463',
    lineId: 'fadl20402',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: "Febria Citra Mutma'innah",
    code: 'CIT',
    phoneNumber: '085600075015',
    lineId: '@febriactraa',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Adinda Sekar Santia',
    code: 'DIN',
    phoneNumber: '081220057992',
    lineId: 'adinda149',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1Bx-XDJ4aUhCBoTa2dBLT9ndmU6_M_ea_?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Andre Prasetyo',
    code: 'AND',
    phoneNumber: '082132221559',
    lineId: 'andre._.prasetyo',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1ldg96uBAW8ZiK1fdJnqDfgyc4SXMaH1c?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Cahaya Irham Wirawan',
    code: 'CCC',
    phoneNumber: '081572712655',
    lineId: 'cahaya_gc',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1RCDKGZUUNoPk9Vr71I4avsdWLeyKuKYW?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Elsi Purbowati',
    code: 'EPW',
    phoneNumber: '08137735617',
    lineId: 'elsipurbowati',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/11W2_5DAu7SL0ljzpaLDcI0sh0RZxHwY5?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Fika Triana',
    code: 'FIK',
    phoneNumber: '082285690257',
    lineId: 'trianafika',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1VdmoqSIl06THmpjsE4b9p1YHnClKCUDv',
    profilePictureUrl: null,
  },
  {
    name: 'Siti Ashila Farikha Mayundri',
    code: 'CIA',
    phoneNumber: '082176171422',
    lineId: 'shtyuw_',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1q_8Y_aoi7RysAdSLHIYDUQJELXurPkuG?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Qualita Imani Pradharona',
    code: 'RON',
    phoneNumber: '085710557883',
    lineId: 'ronashakyra',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1P923FUmEDfKej-u7R8CsplTDBfmJuIOs?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Muhammad Fikri Reynaldi',
    code: 'KRI',
    phoneNumber: '081298402307',
    lineId: 'mfikrnld17',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1z0Lnmb8_DGp19rDt7BXTplVhs9kLTCRM',
    profilePictureUrl: null,
  },
  {
    name: 'Maulana Fauzan Athalla Halinda',
    code: 'ATA',
    phoneNumber: '085322394594',
    lineId: 'athallahalinda',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/16hR9Dkt1mWUHeRr5d0SopHvrVqtwIUmY?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Firda Rizki Nur Hanifa',
    code: 'FIR',
    phoneNumber: '082245628326',
    lineId: 'firdahnf_',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Fredy Pratama',
    code: 'PRT',
    phoneNumber: '082375356761',
    lineId: 'pratama270.id',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Galih Karya Gemilang',
    code: 'GAL',
    phoneNumber: '085862056069',
    lineId: 'gal_ih13',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Gebby Novalisza',
    code: 'GEB',
    phoneNumber: '081271279779',
    lineId: 'gbynvlszaa',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Hana Merlina Hesti Bestari',
    code: 'HNA',
    phoneNumber: '081314625147',
    lineId: 'merlinhesti_17',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Immanuel Putra Timothy Tambun',
    code: 'MAN',
    phoneNumber: '081366538315',
    lineId: 'immanuel_timothy15',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Inne Rineko Putri',
    code: 'NNE',
    phoneNumber: '082299806581',
    lineId: 'innerineko',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Muhammad Haekal Panderadja Pasi',
    code: 'MHP',
    phoneNumber: '085794172533',
    lineId: 'h120345',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Muhammad Hilmy Aziz',
    code: 'MAZ',
    phoneNumber: '089654491695',
    lineId: 'hilmya05',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Muhammad Iqbal',
    code: 'QBL',
    phoneNumber: '081371814480',
    lineId: '051101iqbal',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Muhammad Raditya Aisy Dharmawan',
    code: 'RAD',
    phoneNumber: '081282114055',
    lineId: 'radityaaisy',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Nabilah Indira Putra',
    code: 'NBL',
    phoneNumber: '081212159195',
    lineId: 'alibhanputra',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Ratika Dwi Anggraini',
    code: 'TIK',
    phoneNumber: '081211654100',
    lineId: 'ratikada',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Naili Ikrimah M. Yanis',
    code: 'NAY',
    phoneNumber: '085256008260',
    lineId: 'nailiikrimah',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Naufal Umar Alghifari',
    code: 'UMR',
    phoneNumber: '08119793335',
    lineId: 'naufalumarcool',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Ni Putu Shivana Ayu Antarini',
    code: 'SHI',
    phoneNumber: '081214212008',
    lineId: 'shivanaaa_21',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Nita Hanifah',
    code: 'RYN',
    phoneNumber: '081312975616',
    lineId: 'nitarv_',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Nurfadhilah Putri Bumi',
    code: 'NFD',
    phoneNumber: '082190331092',
    lineId: 'dhilah_pb',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Qanita Syafiqah Ishak',
    code: 'SYA',
    phoneNumber: '081908186710',
    lineId: 'qanitasyafiqah',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Rahma Dania Aleem Lestari',
    code: 'ALE',
    phoneNumber: '085600671843',
    lineId: 'dniarhm27',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Rayhan Dhafi',
    code: 'RDA',
    phoneNumber: '082211945675',
    lineId: 'rayhandhafi',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Jonathan Vito Setiawan',
    code: 'MNG',
    phoneNumber: '081387337718',
    lineId: 'jonathanvitosetiawan',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Lailatul Rohma',
    code: 'LAI',
    phoneNumber: '081249342514',
    lineId: 'lailatulrhma',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Luthfia Azzahra Kusumawardhani',
    code: 'FIY',
    phoneNumber: '082136141825',
    lineId: 'Fiaaaa123',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Muh. Adrian Hidayat',
    code: 'YAN',
    phoneNumber: '085280184032',
    lineId: 'adrian2509',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: "Muhammad 'Irfan Hafizhuddin",
    code: 'HFZ',
    phoneNumber: '081466772250',
    lineId: 'mhrr_',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Muhammad Andika Naufan Dwiandharu',
    code: 'DWI',
    phoneNumber: '082115561580',
    lineId: 'andikanaufan_d',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Muhammad Daffa Hakiki',
    code: 'DFF',
    phoneNumber: '082147637272',
    lineId: 'daffahakiki',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Sang Ayu Putu Diah Utari',
    code: 'TAR',
    phoneNumber: '085249756189',
    lineId: 'sangayutari69',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Reza Widehan',
    code: 'CAW',
    phoneNumber: '088229851022',
    lineId: 'ressawidehan',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Rezika Ramadhanti',
    code: 'RRZ',
    phoneNumber: '087875235482',
    lineId: 'ririsrezika19',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Rifanisa Azzahra',
    code: 'ZRA',
    phoneNumber: '085214996038',
    lineId: 'rif_anisaa3',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Rivo Rivaldo Achmad Sevano',
    code: 'IPO',
    phoneNumber: '081314597513',
    lineId: 'rivo..',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Rizky Aris Prasetya',
    code: 'IKY',
    phoneNumber: '082230536808',
    lineId: 'rizky.aris123',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Salma Dzikriyah Zulfaa',
    code: 'SDZ',
    phoneNumber: '0895703015958',
    lineId: 'sdzulfaa8',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Salwa Nurhaliza',
    code: 'AWA',
    phoneNumber: '081271086328',
    lineId: 'salwakhh',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Shafa Tanaya Paramesti',
    code: 'SHA',
    phoneNumber: '085772695422',
    lineId: 'shafatanaya',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Sinatryasti Purwi Agfianingrum',
    code: 'SYN',
    phoneNumber: '0895618734334',
    lineId: 'sinatryastipurwi',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Tegar Muhammad Al-Hadie',
    code: 'DIE',
    phoneNumber: '082119751101',
    lineId: '4rgatema',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Yoses Dwi Maheswara',
    code: 'YOS',
    phoneNumber: '089696181416',
    lineId: 'yosesdwi',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Zahrayna Shebina Syabira',
    code: 'SHB',
    phoneNumber: '089632536156',
    lineId: 'zahshe22',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Zaidan Irfandito',
    code: 'LMS',
    phoneNumber: '081281150036',
    lineId: 'zaidairfandito02',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Zaidan Muhammad Mahdi',
    code: 'ZMM',
    phoneNumber: '081290571150',
    lineId: 'zaidanmahdi',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl: null,
    profilePictureUrl: null,
  },
  {
    name: 'Tania Verasta',
    code: 'TAN',
    phoneNumber: '082111892663',
    lineId: 'tania_verasta',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1mVYc13PKePPJln7V0WDZ0e0UDixNB_Sv?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Viny Aulia Sabilla',
    code: 'VAS',
    phoneNumber: '081239288035',
    lineId: 'vasdifferent888',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1tla_NgazZPKmbW0u5-a9BfIJQKIlm94j?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Thalita Dewi Rahmaniar',
    code: 'THA',
    phoneNumber: '082119759796',
    lineId: 'thallitadr',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1F53snSTzB-X8uds8KiqEvholDIALEgcZ?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Zalfa Aurellia',
    code: 'ZAL',
    phoneNumber: '081910100392',
    lineId: 'zalfaaurellia04',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1aIrbLvtz4_uimI2vVBJ2_b-45j7dP4jR?usp=sharing',
    profilePictureUrl: null,
  },
  {
    name: 'Aurellia Fieldza Sendyartha',
    code: 'AFS',
    phoneNumber: '081252375414',
    lineId: 'Afs140202',
    gender: Gender.MALE,
    level: AssistantLevel.JUNIOR,
    feedbackUrl:
      'https://drive.google.com/drive/folders/1HnYDA_r0KGZYHWsLkD2O92FQf2mo02yB?usp=sharing',
    profilePictureUrl: null,
  },
];
