name: Backend (production)
on:
  push:
    branches:
      - main
    paths:
      - "apps/fisdascms-server/**"
jobs:
  deploy-to-heroku:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "fisdascms-server" # Must be unique in Heroku
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          branch: "main"
          appdir: "apps/fisdascms-server"
        env:
          HD_NODE_ENV: ${{ secrets.NODE_ENV }}
          HD_MONGO_URI: ${{ secrets.MONGO_URI }}
          HD_JWT_SECRET: ${{ secrets.JWT_SECRET }}
  deploy-to-railway:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    environment: production
    env:
      working-directory: apps/fisdascms-server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: ${{ env.working-directory }}
        run: yarn install
      - name: Install Railway CLI
        run: yarn global add @railway/cli
      - name: Set up environment variables on Railway
        working-directory: ${{ env.working-directory }}
        run: |
          RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }} railway run railway vars set NODE_ENV=${{ secrets.NODE_ENV }}
          RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }} railway run railway vars set MONGO_URI=${{ secrets.MONGO_URI }}
          RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }} railway run railway vars set JWT_SECRET=${{ secrets.JWT_SECRET }}
      - name: Deploy
        working-directory: ${{ env.working-directory }}
        run: RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }} railway run railway up
