name: Development

on:
  push:
    branches-ignore:
      - main

jobs:
  deploy-to-vercel:
    uses: ./.github/workflows/vercel-deploy.yml
    with:
      environment: development
      vercel-environment: preview
      working-directory: .
    secrets: inherit
