name: Frontend (development)

on:
  push:
    branches-ignore:
      - main
    paths:
      - "apps/fisdascms-client/**"

jobs:
  deploy-to-vercel:
    uses: ./.github/workflows/vercel-deploy.yml
    with:
      environment: development
      vercel-enviroment: preview
      working-directory: apps/fisdascms-client
