name: Production

on:
  push:
    branches:
      - main

jobs:
  deploy-to-vercel:
    uses: ./.github/workflows/vercel-deploy.yml
    with:
      environment: production
      vercel-environment: production
      working-directory: .
    secrets: inherit
