name: Production
on:
  push:
    branches:
      - main
    paths:
      - "apps/fisdascms-server/**"
jobs:
  deploy-server-app:
    name: Deploy server app to Heroku
    runs-on: ubuntu-latest
    environment: fisdascms
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "fisdascms-server" # Must be unique in Heroku
          heroku_email: "izzuzantyaf@gmail.com"
          branch: "main"
          appdir: "apps/fisdascms-server"
        env:
          HD_MONGO_URI: ${{ secrets.MONGO_URI }}
          HD_JWT_SECRET: ${{ secrets.JWT_SECRET }}
