# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Server
on:
  push:
    branches: ["redev"]
jobs:
  test:
    runs-on: ubuntu-latest
    environment: fisdascms-redev
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: "Setup and run tests"
        working-directory: apps/fisdascms-server
        run: |
          yarn install
          yarn test
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment: fisdascms-redev
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "fisdascms-redev" #Must be unique in Heroku
          heroku_email: "izzuzantyaf@gmail.com"
          branch: "redev"
          appdir: "apps/fisdascms-server"
        env:
          HD_MONGO_URI: ${{ secrets.MONGO_URI }}
          HD_JWT_SECRET: ${{ secrets.JWT_SECRET }}
